const JOIN_START = 'JOIN_START'
const JOIN_SUCCESS = 'JOIN_SUCCESS'
const JOIN_FAILED = 'JOIN_FAILED'

const FETCH_GROUPS_START = 'FETCH_GROUPS_START'
const FETCH_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS'
const FETCH_GROUPS_FAILED = 'FETCH_GROUPS_FAILED'

export default {
  JOIN_FAILED,
  JOIN_START,
  JOIN_SUCCESS,
  FETCH_GROUPS_FAILED,
  FETCH_GROUPS_START,
  FETCH_GROUPS_SUCCESS,
}